//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blotters
    {
        public int Id { get; set; }
        public Nullable<int> ViolatorId { get; set; }
        public string ComplainantName { get; set; }
        public string ComplainantAddress { get; set; }
        public Nullable<int> ComplaintTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string BlotterId { get; set; }
        public string IncidentPlace { get; set; }
        public Nullable<bool> IsSettled { get; set; }
        public Nullable<bool> IsCleared { get; set; }
    
        public virtual PersonalInformations PersonalInformations { get; set; }
        public virtual ComplaintTypes ComplaintTypes { get; set; }
    }
}
