//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cedulas
    {
        public int Id { get; set; }
        public Nullable<int> PersonalInformationId { get; set; }
        public Nullable<int> CtcNo { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public string PlaceIssued { get; set; }
        public Nullable<decimal> BasicTax { get; set; }
        public Nullable<decimal> AdditionalTax { get; set; }
        public Nullable<decimal> GrossReceipt { get; set; }
        public Nullable<decimal> GrossEarning { get; set; }
        public Nullable<decimal> IncomeRealPropertyIndividual { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual PersonalInformations PersonalInformations { get; set; }
    }
}
