//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certifications
    {
        public int Id { get; set; }
        public int PersonalInformationId { get; set; }
        public Nullable<int> CertificationTypeId { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CTCNo { get; set; }
        public string OrNo { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
    
        public virtual PersonalInformations PersonalInformations { get; set; }
        public virtual CertificationTypes CertificationTypes { get; set; }
    }
}
