//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        public int Id { get; set; }
        public string MeetingId { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string Description { get; set; }
        public string Createdby { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public string GroupId { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
